#!/bin/bash

COMPOSE_DOCKER_CLI_BUILD=1 \
DOCKER_BUILDKIT=1 \
TUNNEL_PASS=`cat creds.env | grep "TUNNEL_PASS" | cut -d "=" -f2` \
DOMAIN=`cat creds.env | grep "DOMAIN" | cut -d "=" -f2` \
docker compose -f framework/infra/compose/agent-api-compose.yml \
               -f framework/infra/compose/owui-compose.yml \
               -f framework/infra/compose/agent-ui-compose.yml \
               -f framework/infra/compose/searxng-compose.yml \
               -f framework/infra/compose/prefect-compose.yml \
               -f framework/infra/compose/proxy-compose.yml $@


## deploy by profiles or indivual services

# searxng
# ./runner --profile searxng up

# agent ui
# ./runner --profile agent-ui up

# llm app
# ./runner --profile llm-app up

#agent api
# ./runner --profile agent-api up